# Generated by Django 2.0.8 on 2021-07-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcourt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='TestUser',
        ),
    ]
