# Generated by Django 3.2.5 on 2021-07-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcourt', '0002_auto_20210708_0703'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestUser',
            new_name='User',
        ),
    ]
