# Generated by Django 3.2.5 on 2021-07-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcourt', '0003_rename_testuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='info',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
