# Generated by Django 3.2.5 on 2021-07-09 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcourt', '0004_auto_20210708_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fooditems', models.CharField(max_length=100)),
                ('totalamount', models.CharField(max_length=100)),
                ('name', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='foodcourt.user')),
            ],
        ),
    ]
