# Generated by Django 3.2.5 on 2021-07-12 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcourt', '0008_remove_order_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myorder',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('food_items', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='foodcourt.order')),
                ('name', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='foodcourt.user')),
            ],
        ),
    ]
