# Generated by Django 3.2.5 on 2021-07-12 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcourt', '0009_myorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='foodcourt.user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fooditems',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='foodcourt.info'),
        ),
    ]
