# Generated by Django 3.2.5 on 2021-07-12 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcourt', '0010_auto_20210712_0648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myorder',
        ),
    ]
